"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

type ProductDemoEditorProps = {
  projectId: string;
};

const scenes = [
  { id: "hook", title: "Hook", duration: 3, headline: "Meetings shouldn’t create more work." },
  { id: "reveal", title: "Product Reveal", duration: 4, headline: "Meetly turns every meeting into structured insights." },
  { id: "feature", title: "Feature", duration: 5, headline: "Automatic meeting summaries." },
  { id: "benefit", title: "Benefit", duration: 5, headline: "Key decisions and action items. Instantly." },
  { id: "cta", title: "CTA", duration: 4, headline: "Meet less. Get more done." },
];

export default function ProductDemoEditor({ projectId }: ProductDemoEditorProps) {
  const router = useRouter();
  const [activeSceneId, setActiveSceneId] = useState("hook");
  const [headline, setHeadline] = useState(scenes[0].headline);
  const [motion, setMotion] = useState("Standard");
  const [layout, setLayout] = useState("Centered headline");
  const [playing, setPlaying] = useState(false);
  const activeScene = scenes.find((scene) => scene.id === activeSceneId) ?? scenes[0];

  function selectScene(id: string) {
    const scene = scenes.find((item) => item.id === id) ?? scenes[0];
    setActiveSceneId(id);
    setHeadline(scene.headline);
  }

  return <section className="mx-auto max-w-[1440px]"><div className="mb-6 flex flex-col gap-4 rounded-3xl border border-white/10 bg-pricing-bg p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Product Demo Editor</p><h1 className="mt-1 font-display text-2xl font-bold uppercase text-white">Meetly Feature Launch</h1></div><button type="button" onClick={() => router.push(`/dashboard/product-demo/${projectId}/export`)} className="rounded-full bg-primary px-6 py-3 text-sm font-semibold text-black transition hover:bg-primary-dark focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary">Export Video</button></div>

    <div className="grid gap-5 xl:grid-cols-[250px_minmax(0,1fr)_300px]"><aside className="rounded-3xl border border-white/10 bg-pricing-bg p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Scenes</h2><span className="text-xs text-neutral-500">21 sec</span></div><ol className="mt-4 space-y-2">{scenes.map((scene, index) => <li key={scene.id}><button type="button" onClick={() => selectScene(scene.id)} aria-pressed={activeSceneId === scene.id} className={`flex w-full items-center gap-3 rounded-2xl p-3 text-left transition ${activeSceneId === scene.id ? "bg-primary text-black" : "text-neutral-450 hover:bg-white/5 hover:text-white"}`}><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-semibold ${activeSceneId === scene.id ? "bg-black/15" : "bg-white/5 text-primary"}`}>{String(index + 1).padStart(2, "0")}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{scene.title}</span><span className={`mt-1 block text-xs ${activeSceneId === scene.id ? "text-black/60" : "text-neutral-500"}`}>{scene.duration} sec</span></span></button></li>)}</ol><button type="button" onClick={() => router.push(`/dashboard/product-demo/${projectId}/storyboard`)} className="mt-5 w-full rounded-full border border-white/15 px-3 py-2 text-xs font-semibold text-white transition hover:bg-white/10">Edit storyboard</button></aside>

      <section className="flex min-h-[560px] flex-col rounded-3xl border border-white/10 bg-black p-4"><div className="relative flex flex-1 items-center justify-center overflow-hidden rounded-2xl border border-white/10 bg-[radial-gradient(circle_at_50%_20%,#51551c_0%,#1b1d0b_35%,#050505_75%)]"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgb(255_255_255_/_0.04)_1px,transparent_1px),linear-gradient(90deg,rgb(255_255_255_/_0.04)_1px,transparent_1px)] [background-size:32px_32px]" /><div className="relative w-[78%] rounded-2xl border border-white/15 bg-[#101111] p-4 shadow-2xl"><div className="flex gap-1.5 border-b border-white/10 pb-3"><span className="h-2 w-2 rounded-full bg-red-400" /><span className="h-2 w-2 rounded-full bg-amber-300" /><span className="h-2 w-2 rounded-full bg-primary" /></div><div className="grid gap-3 pt-4 sm:grid-cols-[90px_1fr]"><div className="rounded-xl bg-white/5 p-2"><span className="block rounded-md bg-primary px-2 py-1 text-[8px] font-bold text-black">Meetly</span><span className="mt-3 block h-1 rounded bg-white/10" /><span className="mt-2 block h-1 rounded bg-white/10" /><span className="mt-2 block h-1 rounded bg-white/10" /></div><div><span className="block text-[10px] font-semibold text-white">AI Meeting Summary</span><div className="mt-3 rounded-xl border border-primary/30 bg-primary/[.06] p-3"><span className="text-[9px] font-semibold text-primary">SUMMARY READY</span><span className="mt-2 block h-2 w-3/4 rounded bg-white/70" /><span className="mt-2 block h-2 w-full rounded bg-white/20" /><span className="mt-2 block h-2 w-2/3 rounded bg-white/20" /></div></div></div></div><div className="relative mt-8 max-w-lg px-6 text-center"><p className="font-display text-3xl font-bold uppercase leading-tight text-white sm:text-5xl">{headline}</p><p className="mt-4 text-sm text-white/60">{activeScene.title} · {activeScene.duration} seconds</p></div><button type="button" onClick={() => setPlaying(!playing)} aria-label={playing ? "Pause preview" : "Play preview"} className="absolute bottom-6 left-6 flex h-12 w-12 items-center justify-center rounded-full bg-primary text-lg text-black shadow-lg transition hover:scale-105">{playing ? "Ⅱ" : "▶"}</button></div><div className="mt-4 flex items-center gap-3"><span className="text-xs text-neutral-500">00:00</span><div className="h-1 flex-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-1/5 rounded-full bg-primary" /></div><span className="text-xs text-neutral-500">00:21</span></div></section>

      <aside className="rounded-3xl border border-white/10 bg-pricing-bg p-5"><h2 className="text-sm font-semibold text-white">Edit scene</h2><p className="mt-1 text-xs text-neutral-500">{activeScene.title} · {activeScene.duration} sec</p><div className="mt-6 border-b border-white/10 pb-5"><label className="block"><span className="text-xs font-semibold uppercase tracking-[0.14em] text-neutral-450">Headline</span><textarea value={headline} onChange={(event) => setHeadline(event.target.value)} className="mt-2 min-h-24 w-full resize-y rounded-2xl border border-white/10 bg-black px-3 py-3 text-sm leading-6 text-white outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /></label><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => setHeadline(headline.split(" ").slice(0, 5).join(" "))} className="rounded-full bg-white/5 px-3 py-2 text-xs font-semibold text-white transition hover:bg-white/10">Shorter</button><button type="button" onClick={() => setHeadline("Transform every meeting into clear action.")} className="rounded-full bg-white/5 px-3 py-2 text-xs font-semibold text-white transition hover:bg-white/10">Rewrite</button></div></div><div className="border-b border-white/10 py-5"><h3 className="text-xs font-semibold uppercase tracking-[0.14em] text-neutral-450">Visual</h3><label className="mt-3 block text-sm font-medium text-white">Layout<select value={layout} onChange={(event) => setLayout(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black px-3 py-2.5 text-sm text-white outline-none focus:border-primary"><option>Centered headline</option><option>Split product UI</option><option>Headline over UI</option></select></label></div><div className="pt-5"><h3 className="text-xs font-semibold uppercase tracking-[0.14em] text-neutral-450">Motion intensity</h3><div className="mt-3 grid grid-cols-3 gap-2">{["Subtle", "Standard", "Energetic"].map((item) => <button key={item} type="button" onClick={() => setMotion(item)} aria-pressed={motion === item} className={`rounded-xl px-2 py-2 text-xs font-semibold transition ${motion === item ? "bg-primary text-black" : "bg-white/5 text-neutral-450 hover:bg-white/10 hover:text-white"}`}>{item}</button>)}</div></div></aside></div>
  </section>;
}
